### ISSUE TITLE
Does not compile in VS2017 15.7.1 Community Edition

### ISSUE THREAD

**Issue by ezeh2** [HJLebbink/vsix-bug-quickinfosession#1]
Please write in documentation, which edition of Visual Studio is required. Community. Professional or Enterprise Edition ?

I get this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.VSSDK.BuildTools.15.7.104\build\Microsoft.VSSDK.BuildTools.props.	VsixBug	C:\Users\ezeh\Source\Repos\vsix-bug-quickinfosession\VsixBug\VsixBug.csproj	218

**Comment by HJLebbink** [comment]
The project is tested in on a Community version (14.7.4), but it should also work on Pro and Enterprise versions too. 

Yes, you will need to resolve the NuGet packages...
